[project]
name = "rag-against-the-machines"
version = "0.2.0"
description = "A RAG system that answers queries related to a codebase"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []


[tool.ruff]
line-length = 79
[tool.ruff.lint]
select = ["E", "F", "B", "I"]

[dependency-groups]
dev = [
    "flake8>=7.3.0",
    "mypy>=2.3.1",
    "pytest>=9.1.1",
    "ruff>=0.16.8",
]

